services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=reservations'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - database-volume:/var/lib/postgresql
volumes:
  database-volume:
